name: CI Cinephoria

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ============================
      # BACKEND
      # # ============================
      # - name: Install backend dependencies
      # #   # working-directory: ./cinephoria-backend
        # run: npm install

      # # - name: Run backend tests
      #  # working-directory: ./cinephoria-backend
      #   run: npm test || echo "No tests"

      # # ============================
      # # FRONTEND ANGULAR
      # # ============================
      # - name: Install frontend dependencies
      # #   # working-directory: ./cinephoria-frontend
      #   run: npm install

      # - name: Build Angular app
      # #   # working-directory: ./cinephoria-frontend
      #   run: npm run build

      # ============================
      # DOCKER CHECK
      # ============================
      - name: Check Docker Compose
        run: docker compose -f docker-compose.prod.yml config

      # ============================
      # BUILD DOCKER IMAGES (optionnel)
      # ============================
      - name: Build Docker images
        run: docker compose -f docker-compose.prod.yml build